
Text = "ali dossani"
print("in morse",Text)
space = Text.replace (" ", " /")
a = space.replace ("a", ".-")
b = a.replace ("b","-...")
c = b.replace ("c","-.-.")
d = c.replace("d","-..")
e = d.replace("e",".")
f = e.replace("f","..-.")
g = f.replace("g","--.")
h = g.replace("h","....")
i = h.replace("i","..")
j = i.replace("j",".---")
k = j.replace("k","-.-")
l = k.replace("l",".-..")
m = l.replace("m","--")
n = m.replace("n","-.")
o = n.replace("o","---")
p = o.replace("p",".--.")
q = p.replace("q","--.-")
r = q.replace("r",".-.")
s = r.replace("s","...")
t = s.replace("t","-")
u = t.replace("u","..-")
v = u.replace("v","...-")
w = v.replace("w",".--")
x = w.replace("x","-..-")
y = x.replace("y","-.--")
z = y.replace("z","--..")
print(z)